[package]
name = "potree-auth"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "potree-auth"

[dependencies]
anyhow = "1.0.97"
async-trait = "0.1.88"
axum = "0.8.3"
http = "1.3.1"
mime = "0.3.17"
mime_guess = "2.0.5"
potree_embed = { git = "https://github.com/cracky-scans/potree.git", branch = "embed-into-rust-crate" }
rust-embed = "8.7.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["fs", "macros", "rt-multi-thread"] }

[dev-dependencies]
axum-test = "17.3.0"
fake = { version = "4.3.0", features = ["derive"] }
mockall = "0.13.1"
tempfile = "3.19.1"
