services:
  potree-auth:
    image: potree-auth:latest
    restart: unless-stopped

    # The externally accessible port of the application.
    ports:
      - "${POTREE_AUTH_PORT_HTTP:-3000}:3000"

    # Various environment variables required by the application. Mostly
    # related to `IdP` configuration. If one of the IdP related env vars
    # are provided then all of the others should be as well. Else the
    # `potree-auth` application won't start.
    environment:
      IDP_URL: ${IDP_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      GROUPS_CLAIM: ${GROUPS_CLAIM}
      EXTERNAL_URL: ${EXTERNAL_URL}
      PROJECTS_DIR: /project_data

    volumes:
      # The local path to the directory into which the project data
      # (point clouds, etc.) will be stored.
      - ${PROJECTS_DIR:?path to project data required}:/project_data
    
    # # Check that the container is ready to accept queries.
    # healthcheck:
    #   test: ["CMD-SHELL", "curl http://localhost:3000/_health | grep true"]
    #   start_period: 3s
    #   interval: 60s
    #   retries: 3
    #   timeout: 2s
